config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :gelatis
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'gelatis#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gelati.rb
class Gelati < ApplicationRecord
    has_one_attached :cover
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gelatis_controller.rb
class GelatisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_gelati, only: %i[ show edit update destroy ]

  # GET /gelatis or /gelatis.json
  def index
    @gelatis = Gelati.all
  end

  # GET /gelatis/1 or /gelatis/1.json
  def show
  end

  # GET /gelatis/new
  def new
    @gelati = Gelati.new
  end

  # GET /gelatis/1/edit
  def edit
  end

  # POST /gelatis or /gelatis.json
  def create
    @gelati = Gelati.new(gelati_params)

    respond_to do |format|
      if @gelati.save
        format.html { redirect_to @gelati, notice: "Gelati was successfully created." }
        format.json { render :show, status: :created, location: @gelati }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gelati.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gelatis/1 or /gelatis/1.json
  def update
    respond_to do |format|
      if @gelati.update(gelati_params)
        format.html { redirect_to @gelati, notice: "Gelati was successfully updated." }
        format.json { render :show, status: :ok, location: @gelati }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gelati.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gelatis/1 or /gelatis/1.json
  def destroy
    @gelati.destroy
    respond_to do |format|
      format.html { redirect_to gelatis_url, notice: "Gelati was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gelati
      @gelati = Gelati.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gelati_params
      params.require(:gelati).permit(:nome, :ingredienti, :calorie, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gelatis_helper.rb
module GelatisHelper
end

app/views/gelatis/_form.html.erb
<%= form_with(model: gelati) do |form| %>
  <% if gelati.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gelati.errors.count, "error") %> prohibited this gelati from being saved:</h2>

      <ul>
        <% gelati.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="container-fluid">
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :nome, class: 'form-label'%>
          <%= form.text_field :nome, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :ingredienti, class: 'form-label'%>
          <%= form.text_field :ingredienti, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :calorie, class: 'form-label' %>
          <%= form.number_field :calorie, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :cover, class: 'form-label' %>
          <%= form.file_field :cover, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>



  <div class="actions">
    <%= form.submit 'Crea/modifica gelato', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/gelatis/edit.html.erb
<h1>Editing Gelati</h1>

<%= render 'form', gelati: @gelati %>

<%= link_to 'Mostra', @gelati, class: 'btn btn-primary' %> |
<%= link_to 'Indietro', gelatis_path, class: 'btn btn-primary' %>

app/views/gelatis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gelatis</h1>

<% if user_signed_in? %>
Benvenuto <b><%= current_user.email %></b>!
<br><%= link_to "Loggautati", destroy_user_session_path, method: :delete %>
<% end %>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Foto</th>
      <th scope="col">Nome</th>
      <th scope="col">Ingredienti</th>
      <th scope="col">Calorie</th>
    </tr>
  </thead>
  <tbody>
  <% @gelatis.each do |gelati| %> 
    <tr>
      <td>
        <% if gelati.cover.attached? %>
        <%= link_to (image_tag url_for(gelati.cover)), gelati %>
        <% end %>
      </td>
    
    
      <td><%= gelati.nome %></td>
    
    
      <td><%= gelati.ingredienti %></td>
    
    
      <td><%= gelati.calorie %></td>
    
      <td><%= link_to 'Modifica', edit_gelati_path(gelati), class: 'btn btn-primary' %></td>  
    
      <td><%= link_to 'Distruggi', gelati, method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'btn btn-danger' %></td>  

      </tr>
    <% end %>  
  </tbody>
</table>


<br>

<%= link_to 'Nuovo Gelato', new_gelati_path, class: 'btn btn-success' %>

app/views/gelatis/new.html.erb
<h1>New Gelati</h1>

<%= render 'form', gelati: @gelati %>

<br>

<%= link_to 'Indietro', gelatis_path, class: 'btn btn-primary' %>

app/views/gelatis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @gelati.cover.attached? %>
  <%= image_tag url_for(@gelati.cover) %>
  <% end %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @gelati.nome %>
</p>

<p>
  <strong>Ingredienti:</strong>
  <%= @gelati.ingredienti %>
</p>

<p>
  <strong>Calorie:</strong>
  <%= @gelati.calorie %>
</p>

<%= link_to 'Modifica', edit_gelati_path(@gelati), class: 'btn btn-primary' %> |
<%= link_to 'Indietro', gelatis_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Gelati</title>
  </head>
  <body>

  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/gelatis">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/gelatis/new">Nuovo gelato</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %>
    <p class="alert"><%= alert %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>




    

    